name: Tag and Release

on:
  push:
    branches:
      - main
      - master

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Calculate next version
        id: next_version
        run: |
          echo "NEXT_VERSION=$(git describe --tags --abbrev=0 | awk -F. -v OFS=. '{$NF++;print}')" >> $GITHUB_ENV

      - name: Create new tag
        run: |
          git tag ${{ env.NEXT_VERSION }}
          git push origin ${{ env.NEXT_VERSION }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEXT_VERSION }}
          release_name: Release ${{ env.NEXT_VERSION }}
          draft: false
          prerelease: false
